<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Lista de Documentos Protocolados</h3>
                <i class="fa fa-list"></i> <?=$this->view->title;?><br>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Número</th> 
                            <th>Tipo</th> 
                            <th>Valor (R$)</th> 
                            <th>OM</th>
                            <th>Status</th>
                            <th>Doc. Resultante</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                        <tr>
                            <td><?=$this->valueLight($value['number'], $this->view->busca);?></td> 
                            <td><?=$value['type'];?></td> 
                            <td><?='R$ '.$this->valueLight(number_format($value['value'], 2, ',', '.'), $this->view->busca);?></td> 
                            <td><?=$value['om'];?></td> 
                            <td><?=$this->valueLight($value['status'], $this->view->busca);?></td> 
                            <td><?=$this->valueLight($value['docresult'], $this->view->busca);?></td> 
                            <td>
                                <a href="<?=$this->view->routeIndex;?>historico/id/<?=$value['connect'];?>" class="btn btn-success">
                                    <i class="fa fa-eye"></i> Histórico do Doc.
                                </a>
                                <?php if (isset($_SESSION['token'])): ?>
                                <a href="<?=APPDIR;?>registros/status/id/<?=$value['connect'];?>" class="btn btn-info">
                                    <i class="fa fa-plus-square"></i> Adicionar Status
                                </a>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                
                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?=$this->view->controller;?>visualizar/busca/<?=$this->view->busca;?>/pagina/<?=$this->view->btn['previus'];?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                        <li><a href="<?=$this->view->controller;?>visualizar/busca/<?=$this->view->busca;?>/pagina/<?=$value;?>"><?=$value;?></a></li>
                        <?php endforeach;?>
                        <li>
                            <a href="<?=$this->view->controller;?>visualizar/busca/<?=$this->view->busca;?>/pagina/<?=$this->view->btn['next'];?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->