<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?=$this->view->title?></h5>
                
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Edição
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?=$this->view->controller;?>altera/" method="post" id="form">
                        <input type="hidden" name="id" value="<?=$this->view->result['id'];?>">
                        <div class="row">
                            <div class="col-lg-6">

                                <div class="form-group">
                                    <label>Número</label>
                                    <input type="text"
                                           id="number"
                                           name="number"
                                           placeholder="Número do Documento"
                                           class="form-control"
                                           maxlength="10"
                                           value="<?=$this->view->result['number'];?>"
                                           required>
                                </div>

                                <div class="form-group">
                                    <label>OM</label>
                                    <select name="om"
                                            id="om"
                                            class="form-control"
                                            required>
                                        <?php foreach ($this->view->resultOm as $key => $value): ?>
                                        <option value="<?= $value['initials']; ?>" <?=($this->view->result['om'] == $value['initials']) ? 'selected' : ''; ?>>
                                            <?= $value['initials']; ?>
                                        </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Data/Hora</label>
                                    <input type="text"
                                           id="time"
                                           name="time"
                                           placeholder="Data/Hora do Status (dd/mm/aaaa-00:00)"
                                           class="form-control"
                                           maxlength="16"
                                           value="<?=date('d-m-Y H:i', $this->view->result['time']);?>"
                                           required>
                                </div>
                                
                                
                            </div>

                            <div class="col-lg-6">
                                
                                <div class="form-group">
                                    <label>Tipo</label>
                                    <input type="text"
                                           id="type"
                                           name="type"
                                           placeholder="Tipo do Documento"
                                           class="form-control"
                                           maxlength="20"
                                           value="<?=$this->view->result['type'];?>"
                                           required>
                                </div>
                                
                                <div class="form-group">
                                    <label>Valor (R$)</label>
                                    <input type="text"
                                           id="value"
                                           name="value"
                                           placeholder="Valor em Reais"
                                           class="form-control"
                                           maxlength="14"
                                           value="<?=number_format($this->view->result['value'], 2, ',', '.');?>"
                                           required>
                                </div>

                                <div class="form-group">
                                    <label>Status</label>
                                    <select name="status"
                                            id="status"
                                            class="form-control"
                                            required>
                                        <?php foreach ($this->view->resultStatus as $key => $value): ?>
                                        <option value="<?= $value['initials']; ?>" <?=($this->view->result['status'] == $value['initials']) ? 'selected' : ''; ?>>
                                            <?= $value['initials']; ?>
                                        </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <br>
                                    <button class="btn btn-primary"><i class="fa fa-check"></i> Registrar</button>
                                    <a href="<?=$this->view->controller;?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                </div>

                            </div>
                        </div>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
