<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Lista de Documentos Protocolados</h3>
                <i class="fa fa-list"></i> <?=$this->view->title;?><br>
                <a href="<?=$this->view->controller;?>status/id/<?=$this->view->result[0]['connect'];?>" class="btn btn-info">
                    <i class="fa fa-plus-square"></i> Adicionar Status
                </a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Número</th> 
                            <th>Tipo</th> 
                            <th>Valor (R$)</th> 
                            <th>OM</th>
                            <th>Status</th>
                            <th>Nº Doc</th>
                            <th>Data/Hora</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                        <tr>
                            <td><?=$value['number'];?></td> 
                            <td><?=$value['type'];?></td> 
                            <td><?='R$ '.number_format($value['value'], 2, ',', '.');?></td> 
                            <td><?=$value['om'];?></td>
                            <td><?=$value['status'];?></td>
                            <td><?=$value['docresult'];?></td>
                            <td><?=date('d-m-Y H:i', $value['time']);?></td>
                            <td>
                                <a href="#"
                                   onclick="confirmar('Deseja REMOVER este registro?', '<?=$this->view->controller;?>eliminar/id/<?=$value['id'];?>')"
                                   class="btn btn-danger">
                                    <i class="fa fa-trash"></i> Eliminar
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                
                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?=$this->view->controller;?>historico/id/<?=$this->view->result[0]['connect'];?>/pagina/<?=$this->view->btn['previus'];?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                        <li><a href="<?=$this->view->controller;?>historico/id/<?=$this->view->result[0]['connect'];?>/pagina/<?=$value;?>"><?=$value;?></a></li>
                        <?php endforeach;?>
                        <li>
                            <a href="<?=$this->view->controller;?>historico/id/<?=$this->view->result[0]['connect'];?>/pagina/<?=$this->view->btn['next'];?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->