<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Lista de Documentos Protocolados</h3>
                <i class="fa fa-list"></i> <?=$this->view->title;?><br>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Número</th> 
                            <th>Tipo</th> 
                            <th>Valor (R$)</th> 
                            <th>OM</th> 
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                        <tr>
                            <td><?=$value['number'];?></td> 
                            <td><?=$value['type'];?></td> 
                            <td><?='R$ '.number_format($value['value'], 2, ',', '.');?></td> 
                            <td><?=$value['om'];?></td> 
                            <td>
                                <a href="<?=$this->view->controller;?>historico/id/<?=$value['connect'];?>" class="btn btn-success no-print">
                                    <i class="fa fa-eye"></i> Visualizar Histórico do Documento
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                
                <nav class="no-print">
                    <ul class="pagination">
                        <li>
                            <a href="<?=$this->view->controller;?>protocolado/om/<?=$this->view->result[0]['om'];?>/pagina/<?=$this->view->btn['previus'];?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                        <li><a href="<?=$this->view->controller;?>protocolado/om/<?=$this->view->result[0]['om'];?>/pagina/<?=$value;?>"><?=$value;?></a></li>
                        <?php endforeach;?>
                        <li>
                            <a href="<?=$this->view->controller;?>protocolado/om/<?=$this->view->result[0]['om'];?>/pagina/<?=$this->view->btn['next'];?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->